api/config/routes.rb
Rails.application.routes.draw do
  root to: "admin/dashboard#index"

  get "admin" => "admin/dashboard#index"

  devise_for :users
  devise_scope :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  namespace :admin do
    resources :posts
    resources :categories
  end

  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

api/app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :category
end

api/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  layout "admin"

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id, :image)
    end
end

api/app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[ show ]
  include Rails.application.routes.url_helpers

  # GET /posts
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  def show
  end

  # POST /posts
  # def create
  #   @post = Post.new(post_params)

  #   if @post.save
  #     render json: @post, status: :created, location: api_v1_post_url(@post)
  #   else
  #     render json: @post.errors, status: :unprocessable_entity
  #   end
  # end

  # PATCH/PUT /posts/1
  # def update
  #   if @post.update(post_params)
  #     render json: @post
  #   else
  #     render json: @post.errors, status: :unprocessable_entity
  #   end
  # end

  # DELETE /posts/1
  # def destroy
  #   @post.destroy!
  # end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # def post_params
  #   params.require(:post).permit(:title, :body)
  # end
end

api/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id)
    end
end

api/app/helpers/posts_helper.rb
module PostsHelper
end

api/app/views/admin/posts/_form.html.erb
<%= form_with(model: [:admin, post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-6">
    <div class="mb-4">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-4">
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="mb-4">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="mb-4">
      <%= form.label :category_id, 'Category', style: 'display: block' %>
      <%= form.collection_select :category_id, @categories, :id, :name, { prompt: 'Select a Category'} ,{ class: "form-select" } %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

api/app/views/admin/posts/_post.html.erb
<tr id="<%= dom_id post %>">
  <th scope="row"><%= post.id %></th>
  <td><%= link_to post.title, admin_post_path(post.id) %></td>
  <td><%= post.content %></td>
  <td><%= post.category.name %></td>
</tr>

api/app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", admin_post_path(@post) %> |
  <%= link_to "Back to posts", admin_posts_path %>
</div>

api/app/views/admin/posts/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Posts</h1>
  <%= link_to "New post", new_admin_post_path, class: "d-sm-inline-block btn btn-sm btn-primary shadow-sm" %>
</div>

<div class="row">
  <div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4" style="min-height: 400px">
      <div id="posts" class="me-2 ms-2" >
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Titel</th>
              <th scope="col">Content</th>
              <th scope="col">Category</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <%= render post %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

api/app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", admin_posts_path %>
</div>

api/app/views/admin/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<p>ID: <%= @post.id %></p>
<p>Title: <%= @post.title %></p>
<p>Content: <%= @post.content %></p>
<% if @post.image.attached? %>
  <%= image_tag @post.image, style: "width: 300px; height: auto" %>
<% end %>
<p>Category Name: <%= @post.category.name %></p>
<p>Created at: <%= @post.created_at %></p>

<div>
  <%= link_to "Edit this post", edit_admin_post_path(@post), class: "btn btn-primary"  %> |
  <%= link_to "Back to posts", admin_posts_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this post", admin_post_path(@post), method: :delete, class: "btn btn-danger mt-4" %>
</div>