api/config/routes.rb
Rails.application.routes.draw do
  root to: "admin/dashboard#index"

  get "admin" => "admin/dashboard#index"

  devise_for :users
  devise_scope :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  namespace :admin do
    resources :posts
    resources :categories
  end

  namespace :api do
    namespace :v1 do
      resources :posts
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

api/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

api/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  layout "admin"

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

api/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

api/app/helpers/categories_helper.rb
module CategoriesHelper
end

api/app/views/admin/categories/_category.html.erb
<tr id="<%= dom_id category %>">
  <th scope="row"><%= category.id %></th>
  <td><%= link_to category.name, admin_category_path(category.id) %></td>
  <td><%= category.created_at %></td>
</tr>

api/app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-6">
    <div class="mb-4">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "form-control"  %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

api/app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

api/app/views/admin/categories/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Categories</h1>
  <%= link_to "New category", new_admin_category_path, class: "d-sm-inline-block btn btn-sm btn-primary shadow-sm" %>
</div>

<div class="row">
  <div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4" style="min-height: 400px">
      <div id="posts" class="me-2 ms-2" >
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Created At</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <%= render category %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

api/app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

api/app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<p>ID: <%= @category.id %></p>
<p>Name: <%= @category.name %></p>
<p>Created at: <%= @category.created_at %></p>

<div>
  <%= link_to "Edit", edit_admin_category_path(@category), class: "btn btn-primary" %> |
  <%= link_to "Back to categories", admin_categories_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy", admin_category_path(@category), method: :delete, class: "btn btn-danger mt-4" %>
</div>